### ISSUE TITLE
Take OS into account

### ISSUE THREAD

**Issue by Zae** [lightswitch05/php-version-audit#5]
Right now the command will fail if there are any CVE for the current PHP version. But some CVE only apply to a specific OS. It would be nice if there was a flag that would allow me to ignore CVE that do not apply to my current OS.

**Comment by lightswitch05** [comment]
Thanks for the input @Zae, this is an interesting request and I can see how it would be useful to you. However, I think the feature is best served outside of PHP Version. The great thing about this tool is that its designed for scripting use. Here is how you could solve your problem using scripting.

Suppose you are running PHP 7.4.0 and you want to ignore CVE `CVE-2019-11044` (which is related to Windows OS). Just running PHP Version Audit currently gives this output (CVE details are null at the moment because they are brand new CVEs that haven't been published in the CVE database yet).

```bash
~$ docker run --rm lightswitch05/php-version-audit:latest --version=7.4.0
{
    "auditVersion": "7.4.0",
    "hasVulnerabilities": true,
    "hasSecuritySupport": true,
    "hasActiveSupport": true,
    "isLatestPatchVersion": false,
    "isLatestMinorVersion": false,
    "isLatestVersion": false,
    "latestPatchVersion": "7.4.1",
    "latestMinorVersion": "7.4.1",
    "latestVersion": "7.4.1",
    "activeSupportEndDate": "2021-11-28T00:00:00+0000",
    "securitySupportEndDate": "2022-11-28T00:00:00+0000",
    "vulnerabilities": {
        "CVE-2019-11044": null,
        "CVE-2019-11045": null,
        "CVE-2019-11046": null,
        "CVE-2019-11047": null,
        "CVE-2019-11049": null,
        "CVE-2019-11050": null
    }
}
```

You can then pipe that JSON into a great little command line tool called [jq](https://stedolan.github.io/jq/) and filter out any CVE that you do not care about:

```bash
~$ docker run --rm lightswitch05/php-version-audit:latest --version=7.4.0 | jq 'del(.vulnerabilities["CVE-2019-11044"])'
{
  "auditVersion": "7.4.0",
  "hasVulnerabilities": true,
  "hasSecuritySupport": true,
  "hasActiveSupport": true,
  "isLatestPatchVersion": false,
  "isLatestMinorVersion": false,
  "isLatestVersion": false,
  "latestPatchVersion": "7.4.1",
  "latestMinorVersion": "7.4.1",
  "latestVersion": "7.4.1",
  "activeSupportEndDate": "2021-11-28T00:00:00+0000",
  "securitySupportEndDate": "2022-11-28T00:00:00+0000",
  "vulnerabilities": {
    "CVE-2019-11045": null,
    "CVE-2019-11046": null,
    "CVE-2019-11047": null,
    "CVE-2019-11049": null,
    "CVE-2019-11050": null
  }
}
```

Now, `CVE-2019-11044` will always be removed from the output. And the great thing about it is that once your PHP version gets an update and it no longer vulnerable to `CVE-2019-11044`, then command will still run successfully.

It does sound like your might be taking advantage of the `--fail-security` flag to generate an exit code if there are any vulnerabilities found. To reproduce that functionality with `CVE-2019-11044` being ignored, you can make further use of jq:

```bash
~$ docker run --rm lightswitch05/php-version-audit:latest --version=7.4.0 | jq --exit-status 'del(.vulnerabilities["CVE-2019-11044"]) | .vulnerabilities | length == 0'
false
``` 

The above example first filters out CVE-2019-11044 and then checks to see if the `.vulnerabilities` list is empty. If it is empty, it will echo `true` and produce a `0` exit code (success). If it is not empty, as in the example, it will echo `false` and produce a `1` exit code (error).

I hope this helps address your request and use case.

**Comment by Zae** [comment]
Hi @lightswitch05 ,

Thanks for the detailed reply, I am indeed trying to use the --fail-security flag.

Using manual filtering of the CVE's using something like jq would work but would also mean that I would manually have to check all the CVE's and add them to my whitelist every time there is a new CVE.

That's why it would be nice if php-version-audit could automate this for me with a new flag to ignore other OS's than mine.

**Comment by lightswitch05** [comment]
@Zae thanks for the clarification that you want the tool to auto filter for you. I unfortunately, I don’t believe it’s possible to automate that. In fact, the windows specific CVE I mentioned above (CVE-2019-11044) is still not even listed in the National  Vulnerability Database- so even if I felt confident that I could parse out the OS details- it wouldn’t even be possible until weeks after the CVE patch were released- making the usefulness of such a feature basically useless.
